# Generated by Django 4.2.3 on 2023-07-30 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_name'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento'),
        ),
    ]
