# Generated by Django 4.2.3 on 2023-07-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
