# Generated by Django 4.2.3 on 2023-08-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_empleado_hojavida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='hojaVida',
        ),
    ]
