# Generated by Django 4.2.3 on 2023-08-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_empleado_hojavida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Programador(a)'), ('4', 'Otro')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
