# Generated by Django 4.2.3 on 2023-08-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nombreCompleto',
            field=models.CharField(blank=True, max_length=120, verbose_name='nombre completo'),
        ),
    ]
