# Generated by Django 4.2.3 on 2023-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('shortName', models.CharField(max_length=20, verbose_name='Nombre corto')),
                ('active', models.BooleanField(default=False, verbose_name='Anulado')),
            ],
        ),
    ]
