# Generated by Django 4.2.3 on 2023-07-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
