# Generated by Django 4.2.3 on 2023-07-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
