# Generated by Django 4.2.3 on 2023-08-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_departamento_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'mi Departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'shortName')},
        ),
    ]
