# Generated by Django 4.2.3 on 2023-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
